OnlineExamApplication/code/OnlineExamSystem/OnlineExamSystem/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using BL;
using DataModel;

namespace OnlineExamSystem.Controllers
{
    public class BaseController : Controller
    {
        public BaseController()
        {
            ViewBag.JSRefNo = ConfigurationManager.AppSettings["JSRefNo"];
        }
        public ActionResult Logout()
        {
            HttpCookie SessionOut = new HttpCookie("UserId");
            SessionOut.Expires = DateTime.Now.AddYears(-365);
            Response.Cookies.Add(SessionOut);
            return RedirectToAction("SignIn", "Login");
        }
        //public void WriteLog(string strMessage)
        //{
        //    try
        //    {
        //        string strLogPath = ConfigurationManager.AppSettings["LogPath"];
        //        if (!System.IO.Directory.Exists(strLogPath))
        //            System.IO.Directory.CreateDirectory(strLogPath);

        //        string strFileName = "Logs_" + DateTime.Now.Day + DateTime.Now.Month + DateTime.Now.Year + ".log";

        //        FileStream fs = new FileStream(strLogPath + "\\" + strFileName,
        //                            FileMode.OpenOrCreate, FileAccess.Write);
        //        StreamWriter m_streamWriter = new StreamWriter(fs);
        //        m_streamWriter.BaseStream.Seek(0, SeekOrigin.End);
        //        m_streamWriter.WriteLine(strMessage + "\n");
        //        m_streamWriter.Flush();
        //        m_streamWriter.Close();
        //    }
        //    catch (Exception)
        //    {
        //    }
        //}

        public void CreateUserCookie(long userId, string fisrtName, string lastName, string profilePicPath, string mobileNo, string emailId, int userTypeId)
        {
            try
            {
                HttpCookie UserId = new HttpCookie("UserId");
                UserId.Value = Convert.ToString(userId);
                UserId.Expires = DateTime.Now.AddYears(365);
                Response.Cookies.Add(UserId);

                HttpCookie FirstName = new HttpCookie("FirstName");
                FirstName.Value = Convert.ToString(fisrtName);
                FirstName.Expires = DateTime.Now.AddYears(365);
                Response.Cookies.Add(FirstName);

                HttpCookie LastName = new HttpCookie("LastName");
                LastName.Value = Convert.ToString(lastName);
                LastName.Expires = DateTime.Now.AddYears(365);
                Response.Cookies.Add(LastName);

                HttpCookie ProfilePicPath = new HttpCookie("ProfilePicPath");
                ProfilePicPath.Value = Convert.ToString(profilePicPath);
                ProfilePicPath.Expires = DateTime.Now.AddYears(365);
                Response.Cookies.Add(ProfilePicPath);

                HttpCookie MobileNo = new HttpCookie("MobileNo");
                MobileNo.Value = Convert.ToString(mobileNo);
                MobileNo.Expires = DateTime.Now.AddYears(365);
                Response.Cookies.Add(MobileNo);

                HttpCookie EmailId = new HttpCookie("EmailId");
                EmailId.Value = Convert.ToString(emailId);
                EmailId.Expires = DateTime.Now.AddYears(365);
                Response.Cookies.Add(EmailId);

                HttpCookie UserTypeId = new HttpCookie("UserTypeId");
                UserTypeId.Value = Convert.ToString(userTypeId);
                UserTypeId.Expires = DateTime.Now.AddYears(365);
                Response.Cookies.Add(UserTypeId);
            }
            catch (Exception)
            {

                throw;
            }
        }

        public static string CalculateAge(string DOB)
        {
            int age = 0;

            try
            {
                DateTime dtDate = DateTime.ParseExact(DOB, "dd-MM-yyyy", null);
                // Save today's date.
                var today = DateTime.Today;
                // Calculate the age.
                age = today.Year - dtDate.Year;
                // Go back to the year the person was born in case of a leap year
                if (dtDate.Date > today.AddYears(-age)) age--;
            }
            catch (Exception ex)
            {

                throw;
            }
            return age.ToString();
        }

        public List<SelectListItem> GetUserTypes()
        {
            UserBL objUserBL = new UserBL();
            List<SelectListItem> lstSelectItem = new List<SelectListItem>();
            try
            {
                List<UserType> lstUserType = objUserBL.GetUserType();

                if (lstUserType != null)
                {
                    lstSelectItem.Add(new SelectListItem { Text = "Select User Type", Value = "0" });
                    foreach (var u in lstUserType)
                    {
                        lstSelectItem.Add(new SelectListItem { Text = Convert.ToString(u.UserTypeName), Value = Convert.ToString(u.UserTypeId) });
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
            return lstSelectItem;
        }

        public List<SelectListItem> GetCourseListItem()
        {
            CourseBL objUserBL = new CourseBL();
            List<SelectListItem> lstSelectItem = new List<SelectListItem>();
            try
            {
                CourseMaster obj = new CourseMaster();
                List<CourseMaster> lstUserType = objUserBL.CRUDCourses(obj, "L");

                if (lstUserType != null)
                {
                    lstSelectItem.Add(new SelectListItem { Text = "Select Course", Value = "" });
                    foreach (var u in lstUserType)
                    {
                        lstSelectItem.Add(new SelectListItem { Text = Convert.ToString(u.CourseName), Value = Convert.ToString(u.CourseId) });
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
            return lstSelectItem;
        }

        public List<SelectListItem> GetAnswerTypeListItem()
        {
            ExamBL objExamBL = new ExamBL();
            List<SelectListItem> lstSelectItem = new List<SelectListItem>();
            try
            {
                AnswerTypeMaster obj = new AnswerTypeMaster();
                List<AnswerTypeMaster> lstUserType = objExamBL.CRUDAnswerTypes(obj, "L");

                if (lstUserType != null)
                {
                    lstSelectItem.Add(new SelectListItem { Text = "Select Answer Type", Value = "" });
                    foreach (var u in lstUserType)
                    {
                        lstSelectItem.Add(new SelectListItem { Text = Convert.ToString(u.AnswerType), Value = Convert.ToString(u.AnswerTypeId) });
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
            return lstSelectItem;
        }

        public List<SelectListItem> GetQuestionListItem(int courseId)
        {
            ExamBL objExamBL = new ExamBL();
            List<SelectListItem> lstSelectItem = new List<SelectListItem>();
            try
            {
                QuestionMaster obj = new QuestionMaster();
                obj.CourseId = courseId;
                List<QuestionMaster> lstUserType = objExamBL.CRUDQuestions(obj, "Q");

                if (lstUserType != null)
                {
                    lstSelectItem.Add(new SelectListItem { Text = "Select Question", Value = "" });
                    foreach (var u in lstUserType)
                    {
                        lstSelectItem.Add(new SelectListItem { Text = Convert.ToString(u.Question), Value = Convert.ToString(u.QuestionId) });
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
            return lstSelectItem;
        }

        public IEnumerable<SelectListItem> GetDropdownList<O>(List<O> context, string text, string value,  string defaultText) where O : class
        {
            IEnumerable<O> result = context;
            var query = from e in result
                        select new
                        {
                            Value = e.GetType().GetProperty(value).GetValue(e, null),
                            Text = e.GetType().GetProperty(text).GetValue(e, null)
                        };

            var ddlList = query.AsEnumerable().Select(s=>new SelectListItem { Value=s.Value.ToString(),Text=s.Text.ToString()}).ToList();
            ddlList.Insert(0,new SelectListItem { Value = "", Text = defaultText });
            return ddlList.AsEnumerable()
                .Select(s => new SelectListItem
                {
                    Value = s.Value.ToString(),
                    Text = s.Text.ToString()
                    
                });
        }
    }
}

OnlineExamApplication/code/OnlineExamSystem/OnlineExamSystem/Controllers/SuperAdminController.cs
using BL;
using DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineExamSystem.Controllers
{
    [SessionAuthorize]
    public class SuperAdminController : BaseController
    {
        public static ExamBL examBL = new ExamBL();
        public ActionResult Dashboard()
        {
            return View();
        }

        public ActionResult StudentDashboard()
        {
            StudentsExams objExam = new StudentsExams();
            objExam.StudentId = long.Parse("0"+Request.Cookies["UserId"].Value) ;
            List <StudentsExams> examList = examBL.CRUDAddExams(objExam, "L");
            return View(examList);
        }

        public ViewResult PersonalNotes()
        {
            return View();
        }

        public ActionResult NoticeBoard()
        {
            return View();
        }
    }
}

OnlineExamApplication/code/OnlineExamSystem/OnlineExamSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/vendors/css/vendor.bundle.base.css">
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/assets/images/favicon.png" />
</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo" href='@Url.Action("Dashboard","Superadmin")'>
                    <img src="~/assets/images/mahaexam-logo.png" alt="mahaexam logo" />
                </a>
                <a class="navbar-brand brand-logo-mini" href='@Url.Action("Dashboard","Superadmin")'>
                    <img src="~/assets/images/mahaexam-logo.png" alt="mahaexam logo" />
                </a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-stretch">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="mdi mdi-menu"></span>
                </button>

                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                            <div class="nav-profile-text">
                                <p class="mb-1 text-black">@Request.Cookies["FirstName"].Value @Request.Cookies["LastName"].Value</p>
                            </div>
                        </a>
                        <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                            <a class="dropdown-item" href="#">
                                <i class="mdi mdi-cached mr-2 text-success"></i>Update Profile
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href='@Url.Action("Logout","Base")'>
                                <i class="mdi mdi-logout mr-2 text-success"></i>Signout
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item nav-profile">
                        <a href="#" class="nav-link">
                            @*<div class="nav-profile-image">
                                    <img src="~/assets/images/faces/face1.jpg" alt="profile">
                                    <span class="login-status online"></span>
                                </div>
                            *@
                            <div class="nav-profile-text d-flex flex-column">
                                <span class="font-weight-bold mb-2">@Request.Cookies["FirstName"].Value @Request.Cookies["LastName"].Value</span>
                                <span class="text-secondary text-small"></span>
                            </div>
                            <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
                        </a>
                    </li>
                    @if (Request.Cookies["UserTypeId"].Value == "1")
                    {
                        <li class="nav-item">
                            <a class="nav-link" href='@Url.Action("Dashboard", "Superadmin")'>
                                <i class="mdi mdi-home menu-icon"></i>
                                <span class="menu-title">Dashboard</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="collapse" href="#ui-admin" aria-expanded="false" aria-controls="ui-admin">
                                <i class="mdi mdi-contacts menu-icon"></i>
                                <span class="menu-title">User</span>
                                <i class="menu-arrow"></i>
                            </a>
                            <div class="collapse" id="ui-admin">
                                <ul class="nav flex-column sub-menu">
                                    <li class="nav-item"><a class="nav-link" href='@Url.Action("UserList", "User")'>Create User</a></li>

                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="collapse" href="#ui-student" aria-expanded="false" aria-controls="ui-student">
                                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
                                <span class="menu-title">Student</span>
                                <i class="menu-arrow"></i>
                            </a>
                            <div class="collapse" id="ui-student">
                                <ul class="nav flex-column sub-menu">
                                    <li class="nav-item"><a class="nav-link" href='@Url.Action("Students","Student")'>Student Registration</a></li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="collapse" href="#ui-exam" aria-expanded="false" aria-controls="ui-exam">
                                <i class="mdi mdi-crosshairs-gps menu-icon"></i>
                                <span class="menu-title">Exams</span>
                                <i class="menu-arrow"></i>
                            </a>
                            <div class="collapse" id="ui-exam">
                                <ul class="nav flex-column sub-menu">
                                    <li class="nav-item"><a class="nav-link" href="@Url.Action("AnswerType", "Exam")">Add Answer Type</a></li>
                                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Questions", "Exam")">Assign Exam Question</a></li>
                                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Answers", "Exam")">Assign Exam Question Answer</a></li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="collapse" href="#ui-course" aria-expanded="false" aria-controls="ui-admin">
                                <i class="mdi mdi-crosshairs-gps menu-icon"></i>
                                <span class="menu-title">Courses</span>
                                <i class="menu-arrow"></i>
                            </a>
                            <div class="collapse" id="ui-course">
                                <ul class="nav flex-column sub-menu">
                                    <li class="nav-item"><a class="nav-link" href='@Url.Action("Course", "Fees")'>Courses</a></li>
                                    <li class="nav-item"><a class="nav-link" href='@Url.Action("Fees", "Fees")'>Fees</a></li>
                                </ul>
                            </div>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" href='@Url.Action("StudentDashboard", "Superadmin")'>
                                <i class="mdi mdi-home menu-icon"></i>
                                <span class="menu-title">Dashboard</span>
                            </a>
                        </li>
                    }
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("PersonalNotes","SuperAdmin")">
                            <i class="mdi mdi-table-large menu-icon"></i>
                            <span class="menu-title">Personal Notes</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("NoticeBoard","SuperAdmin")">
                            <i class="mdi mdi-table-large menu-icon"></i>
                            <span class="menu-title">Notice Board</span>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()

                </div>
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script>
                            All rights reserved
                        </span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center text-muted">Developed By : <a target="_black" href="http://calenturesolutions.com/">Calenture Solutions</a></span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/assets/vendors/chart.js/Chart.min.js"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/assets/js/off-canvas.js"></script>
    <script src="~/assets/js/hoverable-collapse.js"></script>
    <script src="~/assets/js/misc.js"></script>
    @Scripts.Render("~/bundles/jquery")
    <!-- endinject -->

    @RenderSection("scripts", required: false)
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    <!-- End custom js for this page -->
    <script type="text/javascript">
        // $(document).ready(function(){
        //   $( ".nav-link" ).on( "click", function() {
        //     $('.collapse.show').addClass('active-show').parent();
        //     });

        // });

        $(document).ready(function () {
            $('#admin').DataTable();

            $('#student').DataTable();
        });
    </script>

</body>
</html>